cloud:
  aws:
    region:
      static: <aws-region>
      auto: false
    stack:
      auto: false
    credentials:
      access-key: <access-key>
      secret-key: <secret-key>
    sqs:
      url: <sqs-url>

spring.main.allow-bean-definition-overriding: true

server:
  port: 8083
  
logging.level.com.amazonaws.util.EC2MetadataUtils: error
logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error  