cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAXYD3MMNS4CM3EK23
      secret-key: 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

spring.main.allow-bean-definition-overriding: true

server:
  port: 8083
  
logging.level.com.amazonaws.util.EC2MetadataUtils: error
logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error  